### ISSUE TITLE
No token argument when create server

### ISSUE THREAD

**Issue by optimum-web** [gijzelaerr/python-docker-machine#10]
Hi

Is there any way to add token argument for a driver ? 

>>> m.create('test-d', driver='digitalocean', blocking=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/machine/machine.py", line 104, in create
    stdout, stderr, errorcode = self._run_blocking(cmd)
  File "/usr/local/lib/python3.6/site-packages/machine/machine.py", line 56, in _run_blocking
    raise RuntimeError("cmd returned error %s: %s" % (error_code, stderr.decode('utf-8').strip()))
RuntimeError: cmd returned error 1: Error setting machine configuration from flags provided: digitalocean driver requires the --digitalocean-access-token option

**Comment by gijzelaerr** [comment]
currently no, but the API could be extended to pass keyword arguments to the eventual call...

**Comment by optimum-web** [comment]
thanks
